import type { Metadata } from "next";
import { Jomolhari, Josefin_Slab, Josefin_Sans } from "next/font/google";
import "./globals.css";
import SideBar from "./components/sideBar";

const jomolhari = Jomolhari({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-jomolhari",
  display: "swap",
});

const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  variable: "--font-josefin-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Novel",
  description: "Generated by Novel",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jomolhari.variable} ${josefinSans.variable} antialiased`}
      >
        <div className="flex">
          <SideBar />
          {children}
        </div>
      </body>
    </html>
  );
}
